const EditorEvent = {
  justifyCenter: "justifyCenter",
  justifyLeft: "justifyLeft",
  justifyRight: "justifyRight",
  indent: "indent",
  outdent: "outdent",
  fontColor: "forecolor",
  fontSize: "fontsize",
  background: "backColor",
  fontWeightBold: "bold",
  textStyleUnderline: "underline",
  textStyleItalic: "italic",
  copy: "copy",
  cut: "cut",
  paste: "paste",
  selectAll: "selectAll",
  delete: "delete",
  forwardDelete: "forwarddelete",
  removeFormat: "removeFormat",
  redo: "redo",
  undo: "undo",
  formatBlock: "formatblock",
  insertHorizontalrule: "inserthorizontalrule",
  insertOrderedlist: "insertorderedlist",
  insertUnorderedlist: "insertunorderedlist",
  insertCheckbox: "insertCheckbox",
  enableObjectResizing: "enableObjectResizing",
  textStyleStrikeThrough: "strikeThrough",
  insertImage: "insertimage",
  createLink: "createlink",
  unLink: "unlink",
  editing: "focused",
  notEditing: "blur",
  save: "save-note",
  selectionChange: "selection-change",
};

export default EditorEvent;
